# Generated by Django 5.2.4 on 2025-08-01 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('transport_km', models.FloatField()),
                ('electricity_kwh', models.FloatField()),
                ('food_type', models.CharField(max_length=20)),
                ('plastic_grams', models.FloatField(default=0.0)),
            ],
        ),
    ]
